services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SCYLLA_HOST=scylla
    depends_on:
      - scylla

  scylla:
    image: scylladb/scylla:4.5.0
    ports:
      - "9042:9042"
    volumes:
      - scylla_data:/var/lib/scylla
      - ./db/init.cql:/init.cql
    command: --developer-mode=1
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 15s
      timeout: 5s
      retries: 15

  scylla-init:
    image: scylladb/scylla:4.5.0
    depends_on:
      scylla:
        condition: service_healthy
    volumes:
      - ./db/init.cql:/init.cql
    command: /bin/bash -c "echo loading keyspace && cqlsh scylla -f /init.cql"

volumes:
  scylla_data:
